### ISSUE TITLE
Collection Scanning at Startup Ignores Setting to Not Scan When Starting Strawberry

### ISSUE THREAD

**Issue by bama35453** [strawberrymusicplayer/strawberry#1469]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
As default Strawberry will scan the folders containing the personal collection. In the settings there is a switch to turn off this scan on startup.
In case the collection is on a different drive (e.g. on D:\ instead of C:\) the setting is being ignored. So no matter whether the setting is enabled or disabled Strawberry will update the collection.

**To Reproduce**
- Go to settings
- Disable "Scan collection on startup"
- Close Strawberry
- Open Strawberry
- Strawberry will scan the collection if it is stored on another drive than C:\

**Expected behavior**
- Go to settings
- Disable "Scan collection on startup"
- Close Strawberry
- Open Strawberry
- Strawberry will NOT scan the collection if it is stored on a on another drive than C:\ and "Scan collection on startup" is disabled

**Screenshots:**
n/a

**System Information:**
 - Operating system: Windows 11
 - Strawberry Version: 1.0.23

**Additional context**

**Comment by jonaski** [comment]
This is most likely the "Monitor collection for changes" that triggers, try disabling that in the Collection settings and see if the issue is resolved. You can do it manually instead using tools / "Update changed collection folders".

**Comment by bama35453** [comment]
I have disabled all those settings related to scanning / monitoring the collection.
Therefore I don't think it's related to one of those settings.

**Comment by jonaski** [comment]
I can't reproduce this here using a D:. Also, looking at the code I don't see how this can occur if the settings are disabled.

**Comment by bama35453** [comment]
Is there anything like a log within Strawberry I can export for analyzing the issue?

**Comment by bama35453** [comment]
I just did a screenshot of my settings page. I don't know what else I should disable to prevent Strawberry from scanning the collection at every start

![Screenshot Strawberry Settings](https://github.com/user-attachments/assets/5317f9d4-1d8b-486e-af3b-ea89b482f7ce)

**Comment by EauBureau** [comment]
I have this issue too. 
My collection is on a NAS drive. 
This has been going on for quite a while, years I'd guess. I only decided to see if there was a way to fix it today and found this current bug report!

> Also, looking at the code I don't see how this can occur

Over on the forum this guy also has the [issue.](https://forum.strawberrymusicplayer.org/topic/776/prevent-automatic-collection-update?lang=en-US). 
It's definitely happening.

Strawberry Version 1.0.23
Debian 13 Testing
Kernel: 6.9.7-amd64
GNOME 44.9

**Comment by jonaski** [comment]
Are the files placed directly under D:\Music\MP4, or under subdirectories?

**Comment by bama35453** [comment]
In my case within D:\Music\MP3 there is a folder structure "artist\album\titles".
So within D:\Music\MP3 there are > 3,500 folders on artist level and within each of those there are additional folders related to the respective albums.

**Comment by EauBureau** [comment]
Could it be `AlbumCoverLoader` or `strawberry-tagreader` trying to parse the collection?

**Comment by bama35453** [comment]
As far as I can tell everything related to those options should be deactivated. 

My assumption is that the problem is probably more related to using separate drives not directly on the respective machine.

As you mentioned for it occurs with the collection on your NAS.
In my case the collection is located on my OneDrive.

**Comment by guprobr** [comment]
@jonaski does access times, modification times, etc. come into the game whe ntalking about scanning?
Because it would make sense that every time it mounts, it thinks the dir has changed because of different atime, mtime, etc. on the mount point

**Comment by jonaski** [comment]
> Could it be `AlbumCoverLoader` or `strawberry-tagreader` trying to parse the collection?
No. Those are only reading files from disk.
You need to look at `\CollectionWatcher`. It probably occurs here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/collection/collectionwatcher.cpp#L425

**Comment by jonaski** [comment]
It starts a transaction even if the startup option is off, but it shouldn't actually do anything, even when you see "Updating collection", because it's checking the option here: https://github.com/strawberrymusicplayer/strawberry/blob/d3dd26c596dd393c4f6ce3a5c4324a8defb25b9f/src/collection/collectionwatcher.cpp#L433

**Comment by jonaski** [comment]
But I think that whole code path could be skipped, as it's misleading to start a transaction.
I must also be missing something, since I don't see anywhere what's actually causing the songs to be removed.

**Comment by guprobr** [comment]
Its because of latency! The code is correct, but perphaps its not robust in the sense that maybe the resource might be unavailable (its network) ..... Delay scans until Network storage is ready :D  ?

**Comment by jonaski** [comment]
Just to clarify: Is the issue that you are seeing "Updating collection" when Scan on startup is off, or is it that songs from the missing disk are removed from the collection?

**Comment by bama35453** [comment]
In my case I see "Updating collection" even though the scanning of the collection is turned off.

**Comment by jonaski** [comment]
Yes, that's right, but it won't do anything, but I'll fix that. My bad, I assumed you meant that songs were removed too.

**Comment by EauBureau** [comment]
> In my case I see "Updating collection" even though the scanning of the collection is turned off.

Me too. 
I can also see network traffic to/from my NAS drive while it's scanning.

**Comment by jonaski** [comment]
Yes, because it was starting a transaction, it was iterating all the directories and showing updating collection, but it won't do anything. I've fixed it now so it shouldn't do that anymore.

**Comment by EauBureau** [comment]
That's great news. Thank you for taking the time to fix this bug. I'll check it out when the next release hits Debian Testing.
And thanks for Strawberry. It's a great app.. my go-to music player.
Thank you :smile:

**Comment by EauBureau** [comment]
@jonaski I've updated to 1.1.2 and this issue is still happening for me.
It still scans my NAS drive when I open Strawberry. :confused:

**Comment by jonaski** [comment]
Then it's probably not the collection that does it but the playlist. There is a setting in the playlist settings "grey out unavailable songs in playlists on startup", make sure it is not checked (the default is checked).

**Comment by EauBureau** [comment]
`Mark disappeared songs as unavailable`is un-checked but it still happens.
There is one other setting that might be involved: `Expire unavailable songs after 60 days`
Can that be disabled?

It's a samba share. Would samba some how be the cause?

**Comment by jonaski** [comment]
if you un-check the "Mark disappeared songs as unavailable" option, songs will be deleted from the database when they disappear from disk, this is probably not what you want.
The expire feature is only active if both the monitor collection and mark songs unavailable are on (since it would trigger a scan).

**Comment by EauBureau** [comment]
If I quit Strawberry while that start-up collection scan is on going, it throws a few DEBUG lines and ends with an ERROR in the log.

That ERROR process is `CollectionPlaylistItem`

```
Sep 29 03:51:52 hostname org.strawberrymusicplayer.strawberry.desktop[8446]: 03:51:52.201 ERROR CollectionPlaylistItem:46        Could not reload file QUrl("file:///run/user/1000/gvfs/smb-share:server=musicnas,share=music/a song.flac") ""
```

Does that throw any light on it for you?

**Comment by EauBureau** [comment]
@jonaski I've found it :tada: :fireworks: :smile:

It's a loaded playlist is some how causing the collection to be scanned on Strawberry start up.
If there is a playlist loaded when it starts it scans the NAS drive.
When I clear the play list and re-start Strawberry there is no collection scan at start up.

Now here is where the bug is I guess.
If I add the `All Tracks` playlist when Strawberry is already open it does *not* scan the NAS drive at all.
It only scans if it launches with a playlist loaded.

_Background:_
Previously I had my entire (+10k track) collection loaded as the playlist.

I had it that way because the random smart playlists aren't so random! The same songs come up.
Some where in these GitHub issues or on the forum I saw it recommended to load the collection as a playlist and then shuffle the playlist for a better random mix.
