### ISSUE TITLE
Can't filter playlist by "File Name" field anymore

### ISSUE THREAD

**Issue by masavini** [strawberrymusicplayer/strawberry#1523]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I used to filter songs in a playlist by their path. This does not work anymore.

Could this be related to this 1.1.1 enhancements?
`Use same code for collection and playlist filter search.`

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.1.1

**Comment by jonaski** [comment]
This bug is already fixed.

**Comment by masavini** [comment]
this bug is still affecting me even if running the latest version (1.2.3)
is there any setting to enable filtering by file path?
