### ISSUE TITLE
Media playback keys no longer detected

### ISSUE THREAD

**Issue by Cre8or** [strawberrymusicplayer/strawberry#1546]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I'm vaguely paraphrasing, but it seems that a KDE update has changed how events related to media controls are dispatched, and Strawberry is not aware of this change (yet). The behaviour described [in this issue over at the KDE bug tracker](https://bugs.kde.org/show_bug.cgi?id=490569) closely matches my issue:
- Strawberry can be paused via media shortcuts, but not resumed
- Strawberry no longer skips songs in the playlist via media shortcuts ("previous"/"next")

None of these problems seem to occur when I start Strawberry without any additional file arguments (think "double-clicking" the desktop shortcut), and then play music. The issue only occurs when I double-click a music file, which KDE then opens via Strawberry (thus passing the file path as argument). 

My Strawberry/KDE shortcuts are set to default keybindings.

**To Reproduce**
- Ensure Strawberry is not open
- Open a media file with Strawberry (right click -> open with, or any similar method in your distro, so long as Strawberry opens the file immediately on startup)
- Start the first song (if it isn't playing yet)
- Use the system's "Media Play" shortcut key to pause the currently playing song
- Use that same key again to resume the song
- Notice that the song has not resumed
- Manually resume the song via the Strawberry player's UI
- Use the system's "Next track" shortcut key to jump to the next song
- Notice that the playlist hasn't skipped to the next song, and is still playing the first song
- Close Strawberry, and manually reopen it without any file arguments (e.g. desktop shortcut)
- Repeat the above steps and notice the media keys now work again

**Expected behavior**
The listed media buttons should work irrespective of how Strawberry was opened.

**Screenshots:**
![image](https://github.com/user-attachments/assets/cacba0dd-f782-4874-9b5f-6120720bab4b)

**System Information:**
 - Operating system: Arch Linux 6.10.9-arch1-2 / KDE Plasma 6.1.5
 - Strawberry Version: 1.1.2

**Additional context**
~~I suspect there is a problem with how Strawberry detects keypresses, as if I rebind the media shortcuts to miscellaneous keyboard buttons (e.g. `J` / `H` / `K` / etc.), I can use these buttons as expected. *Specifically the media buttons* seem to be the issue. In fact, when I attempt to rebind these keyboard buttons back to the proper media buttons, the window prompting me for a keybind does not register anything, and remains empty:
![image](https://github.com/user-attachments/assets/25f51d1a-0a1f-4ae7-b46d-9df9b2cbb863)~~

See https://bugs.kde.org/show_bug.cgi?id=490569

**Comment by jonaski** [comment]
I've tested global shortscuts on KDE using KGlobalAccel, 3 different keyboard, it's working fine here. KDE Plasma 6.1.5 and KDE Frameworks 6.5.0. I didn't change anything that should affect global shortcuts in version 1.1.2 either.
I suspect this is something to do with the KDE configuration.

**Comment by Cre8or** [comment]
Bit ashamed to admit it, but after a reboot, the issue is now gone. I don't know why the thought hadn't crossed my mind sooner... :grimacing: 

Sorry for wasting your time!

**Comment by Cre8or** [comment]
Hmm, seems like the issue is back, and I can narrow it down to a reproducible error - even across restarts.

When I open Strawberry without passing a media file as argument, the media keys work as expected. I can then add music to it (drag&drop, loading a playlist, etc.)  and use it as expected.

If I however open Strawberry by double-clicking a music file (thus launching Strawberry with a file argument), the media key issues as originally described appear. So it effectively comes down to how I launch the application.

I have done a system update and am still on Strawberry 1.1.2 at this time.

**Comment by Cre8or** [comment]
I'm reopening this issue as the problem still persists in Strawberry v1.1.3.

**Comment by CrimsonKeys** [comment]
I am also having the same issue in Fedora 41 KDE plasma 6.2.4 strawberry v1.2.3. It seems that it is also repeatable on my system only when opening a file directly not when playing after manually opening Strawberry. Like CreBor it also affects VLC, it does not however affect MPV.

**Comment by kyeastmood** [comment]
I have the same issue with Strawberry 1.2.3, the media buttons have never worked for me in Strawberry, though. The media play/pause buttons are not recognized when I press them in the "Global shortcuts" settings page. In the Clementine they work correctly. My system is current Debian Testing with KDE 6.

**Comment by jonaski** [comment]
I can't reproduce this, works here even when opening a file with strawberry from right click menu in dolphin.

**Comment by kyeastmood** [comment]
I found the issue. In the KDE Shortcuts page there was a lower-case "strawberry" entry in the "System Services" section. I'm not sure how it was added there. Both Amarok and Clementine have entries in the "Applications" section instead. So I've also added an entry for Strawberry in the "Applications" section and now it works.
![kde-shortcuts](https://github.com/user-attachments/assets/c350fd41-ad7b-41b9-a82d-2366db75d5f4)

**Comment by jonaski** [comment]
Thanks @kyeastmood 

There was a name mismatch, strawberry with lowercase was used for KGlobalAccel, while Strawberry with capitalized S was used for MPRIS2, maybe that could explain some of the issues. I've fixed this now, if possible try with the latest code from git master, or use the latest from https://builds.strawberrymusicplayer.org/

**Comment by jonaski** [comment]
I don't know why it appeared in the "System services" section, but that it seem to appear correctly under Applications when testing here now after I changed the naming.

**Comment by CrimsonKeys** [comment]
Cheers for the responses I've tried the latest build and It appears to still not be working on my system, I have done further testing and it seems to work fine if I manually set the shortcuts for Strawberry via system settings and it is only when the KDE media controller is trying to control it that it fails. Pause and stop both work however play, next and previous don't work when KDE media controller is being used. As described before though this only seems to be an issue when Strawberry is launched by opening a file and not if it is run manually or if already running then a file is opened.

**Comment by kyeastmood** [comment]
@jonaski I tried to remove both entries (strawberry and Strawberry), but they both always re-appear after I launch the System Settings. But it doesn't seem to be an issue.

I've compiled Strawberry from the main branch and the Play/Pause buttons work but it seems it created its own entry (upper-case) so I had 3 entries. But now I could also remove the manually added entry.

The most-recent build of Strawberry (from the main branch) works both with the entry it created and with the entry I manually added (after I reassign the shortcuts). The distribution-provided Strawberry only works with the entry I added.

So overall the problem for me seems to be fixed, the entry is automatically added to shortcuts and the most recent version improves overall handling of media buttons.

The remaining issues seem to be more likely related to KDE's media playback control.

**Comment by Cre8or** [comment]
I grew tired of having to remember to start Strawberry manually. The amount of times I have opened a song only to later realise that I can't resume it after pausing has just reached its limit.

[Here's my work-around script.](https://gist.github.com/Cre8or/058a87c10fdca70c84d81b299d646cc9)

The idea is that whenever Strawberry is started, the script checks if a media file is to be loaded (e.g. when double-clicking a file), and if so, it delays the loading part (which is done with Strawberry's `--load` command line argument) until Strawberry is running (as loading the file too early causes the media keys issue to occur).

The only necessary tweak is to modify the `Exec=` part of Strawberry's `.desktop` file:
```ini
[Desktop Entry]
Exec=/opt/StrawberryMusicPlayer/strawberry.sh %U # Modify this path to wherever you saved the script
```

**Comment by DarthGandalf** [comment]
For me the "strawberry" with small s has 2 options which are not in Strawberry with big S: "stop after current track" and "show OSD". Hence, these 2 key combinations don't work, because I cannot readd them to the correct Strawberry

**Comment by jonaski** [comment]
I'm just guessing, but I assume CanPlay is emitted before the playlists are loaded causing it to be false, I've added a couple of fixes, delaying command line options + emitting MPRIS2 when playlists are loaded.

**Comment by GitZesty** [comment]
I had Clementine installed and recently started using Strawberry. I couldn't assign certain shortcuts or media keys that were already used by Clementine (but Strawberry didn't let me know; the Shortcuts control panel did let me know, though). I didn't know about checking the KDE shortcuts control panel until I saw @kyeastmood 's screenshot.  After I removed the shortcuts from Clementine then Strawbery's global shortcuts could be assigned and be used.

<img width="1339" height="928" alt="Image" src="https://github.com/user-attachments/assets/7df15a76-490a-4ab1-bfd7-103158a9d85c" />
