### ISSUE TITLE
playlist scrolls up itself after I create another one

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#506]
**To Reproduce**
add to your playlist an amount of songs enough to enable the vertical scroll bar
scroll down
create a new playlist (Strawberry focus the new playlist)
go back to the playlist containing your songs: the playlist scrolled up itself

**Expected behavior**
the playlist should not scroll up itself

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
Fixed https://github.com/strawberrymusicplayer/strawberry/commit/15ddf6ff20a7c986af044ad8425b39f979576528

**Comment by glaubersm** [comment]
This issue is still reproducible with the latest nightly build.

add many songs to your playlist (I added 99)
scroll down and select the last song
create a new playlist
go back to the playlist containing the added songs

Result: the playlist scrolled up and consequently the previously selected song is not visible

**Comment by jonaski** [comment]
It works here. Perhaps we are doing something different. Could show make a video demonstrating it ?

**Comment by glaubersm** [comment]
here is a screen recording
https://www.youtube.com/watch?v=unV9-AMTn_k

**Comment by jonaski** [comment]
I'm doing the exact same thing here and it works fine, when I scroll down to the last song, then create a new playlist, and then switch back to the original playlist I can still see the bottom and the last song (fully scrolled down).
I use XFCE. It has most likely something to do with the desktop environment, Qt version or theme. I already fixed so it restores to the exact same scroll position where it was. In your video it's scrolling down, but to the second last song instead of the last one for some reason I can't explain.

**Comment by glaubersm** [comment]
I  can also reproduce this behavior with Dolphin file manager even on Arch Linux + Gnome 3.36.3.
I think it can be a Qt bug, my Arch runs Qt 5.15, neon unstable shown in my screen recording runs Qt 5.14.2.
